<a href="https://colab.research.google.com/github/NARAYANAN0101/machine-learning-projects/blob/main/housepredictions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import pandas as pd
dataset=pd.read_csv('/content/Delhi house data(1).csv')
dataset

Area  BHK  Bathroom      Furnishing  \
0       800.0    3       2.0  Semi-Furnished   
1       750.0    2       2.0  Semi-Furnished   
2       950.0    2       2.0       Furnished   
3       600.0    2       2.0  Semi-Furnished   
4       650.0    2       2.0  Semi-Furnished   
...       ...  ...       ...             ...   
1254   4118.0    4       5.0     Unfurnished   
1255   1050.0    3       2.0  Semi-Furnished   
1256    875.0    3       3.0  Semi-Furnished   
1257    990.0    2       2.0     Unfurnished   
1258  11050.0    3       3.0     Unfurnished   

                                               Locality  Parking     Price  \
0                                      Rohini Sector 25      1.0   6500000   
1                J R Designers Floors, Rohini Sector 24      1.0   5000000   
2                   Citizen Apartment, Rohini Sector 13      1.0  15500000   
3                                      Rohini Sector 24      1.0   4200000   
4     Rohini Sector 24 carpet area 650 sqft status R...      1.0   6200000   
...                                                 ...      ...       ...   
1254                                  Chittaranjan Park      3.0  55000000   
1255                                  Chittaranjan Park      3.0  12500000   
1256                                  Chittaranjan Park      3.0  17500000   
1257                          Chittaranjan Park Block A      1.0  11500000   
1258                                  Chittaranjan Park      1.0  18500000   

             Status   Transaction           Type  Per_Sqft  
0     Ready_to_move  New_Property  Builder_Floor       NaN  
1     Ready_to_move  New_Property      Apartment    6667.0  
2     Ready_to_move        Resale      Apartment    6667.0  
3     Ready_to_move        Resale  Builder_Floor    6667.0  
4     Ready_to_move  New_Property  Builder_Floor    6667.0  
...             ...           ...            ...       ...  
1254  Ready_to_move  New_Property  Builder_Floor   12916.0  
1255  Ready_to_move        Resale  Builder_Floor   12916.0  
1256  Ready_to_move  New_Property  Builder_Floor   12916.0  
1257  Ready_to_move        Resale  Builder_Floor   12916.0  
1258  Ready_to_move  New_Property  Builder_Floor   12916.0  

[1259 rows x 11 columns]

In [69]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Area         1259 non-null   float64
 1   BHK          1259 non-null   int64  
 2   Bathroom     1257 non-null   float64
 3   Furnishing   1254 non-null   object 
 4   Locality     1259 non-null   object 
 5   Parking      1226 non-null   float64
 6   Price        1259 non-null   int64  
 7   Status       1259 non-null   object 
 8   Transaction  1259 non-null   object 
 9   Type         1254 non-null   object 
 10  Per_Sqft     1018 non-null   float64
dtypes: float64(4), int64(2), object(5)
memory usage: 108.3+ KB


In [70]:
# Select integer columns
int_cols = dataset.select_dtypes(include=['int64'])
# Select float columns
float_cols = dataset.select_dtypes(include=['float64'])
# Select object (string) columns
object_cols = dataset.select_dtypes(include=['object'])

In [71]:
float_cols

Area  Bathroom  Parking  Per_Sqft
0       800.0       2.0      1.0       NaN
1       750.0       2.0      1.0    6667.0
2       950.0       2.0      1.0    6667.0
3       600.0       2.0      1.0    6667.0
4       650.0       2.0      1.0    6667.0
...       ...       ...      ...       ...
1254   4118.0       5.0      3.0   12916.0
1255   1050.0       2.0      3.0   12916.0
1256    875.0       3.0      3.0   12916.0
1257    990.0       2.0      1.0   12916.0
1258  11050.0       3.0      1.0   12916.0

[1259 rows x 4 columns]

In [72]:
object_cols

Furnishing                                           Locality  \
0     Semi-Furnished                                   Rohini Sector 25   
1     Semi-Furnished             J R Designers Floors, Rohini Sector 24   
2          Furnished                Citizen Apartment, Rohini Sector 13   
3     Semi-Furnished                                   Rohini Sector 24   
4     Semi-Furnished  Rohini Sector 24 carpet area 650 sqft status R...   
...              ...                                                ...   
1254     Unfurnished                                  Chittaranjan Park   
1255  Semi-Furnished                                  Chittaranjan Park   
1256  Semi-Furnished                                  Chittaranjan Park   
1257     Unfurnished                          Chittaranjan Park Block A   
1258     Unfurnished                                  Chittaranjan Park   

             Status   Transaction           Type  
0     Ready_to_move  New_Property  Builder_Floor  
1     Ready_to_move  New_Property      Apartment  
2     Ready_to_move        Resale      Apartment  
3     Ready_to_move        Resale  Builder_Floor  
4     Ready_to_move  New_Property  Builder_Floor  
...             ...           ...            ...  
1254  Ready_to_move  New_Property  Builder_Floor  
1255  Ready_to_move        Resale  Builder_Floor  
1256  Ready_to_move  New_Property  Builder_Floor  
1257  Ready_to_move        Resale  Builder_Floor  
1258  Ready_to_move  New_Property  Builder_Floor  

[1259 rows x 5 columns]

In [73]:
float_cols.duplicated().sum()

np.int64(197)

In [74]:
float_cols.isnull().sum()

Area          0
Bathroom      2
Parking      33
Per_Sqft    241
dtype: int64

In [75]:
float_cols.drop_duplicates(inplace=True)
float_cols.duplicated().sum()

np.int64(0)

In [76]:
float_cols.isnull().sum()

Area          0
Bathroom      1
Parking      29
Per_Sqft    145
dtype: int64

In [77]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
float_cols=scalar.fit_transform(float_cols)
float_cols

array([[-0.43068398, -0.52545625, -0.15354226,         nan],
       [-0.46289019, -0.52545625, -0.15354226, -0.43125512],
       [-0.33406533, -0.52545625, -0.15354226, -0.43125512],
       ...,
       [-0.38237465,  0.39301011,  0.13936477, -0.13488411],
       [-0.30830036, -0.52545625, -0.15354226, -0.13488411],
       [ 6.1715903 ,  0.39301011, -0.15354226, -0.13488411]])

In [78]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=5)
float_cols=imputer.fit_transform(float_cols)
float_cols

array([[-0.43068398, -0.52545625, -0.15354226, -0.31569462],
       [-0.46289019, -0.52545625, -0.15354226, -0.43125512],
       [-0.33406533, -0.52545625, -0.15354226, -0.43125512],
       ...,
       [-0.38237465,  0.39301011,  0.13936477, -0.13488411],
       [-0.30830036, -0.52545625, -0.15354226, -0.13488411],
       [ 6.1715903 ,  0.39301011, -0.15354226, -0.13488411]])

In [79]:
data_imputer=scalar.inverse_transform(float_cols)
data_imputer

array([[8.0000e+02, 2.0000e+00, 1.0000e+00, 9.1036e+03],
       [7.5000e+02, 2.0000e+00, 1.0000e+00, 6.6670e+03],
       [9.5000e+02, 2.0000e+00, 1.0000e+00, 6.6670e+03],
       ...,
       [8.7500e+02, 3.0000e+00, 3.0000e+00, 1.2916e+04],
       [9.9000e+02, 2.0000e+00, 1.0000e+00, 1.2916e+04],
       [1.1050e+04, 3.0000e+00, 1.0000e+00, 1.2916e+04]])

In [84]:
float_cols = pd.DataFrame(float_cols, columns=dataset.select_dtypes(include=['float64']).columns)
float_cols.columns

Index(['Area', 'Bathroom', 'Parking', 'Per_Sqft'], dtype='object')

In [83]:
imputed_df = pd.DataFrame(data_imputer,columns=dataset.select_dtypes(include=['float64']).columns)
imputed_df.head()

Area  Bathroom  Parking  Per_Sqft
0  800.0       2.0      1.0    9103.6
1  750.0       2.0      1.0    6667.0
2  950.0       2.0      1.0    6667.0
3  600.0       2.0      1.0    6667.0
4  650.0       2.0      1.0    6667.0

In [85]:
imputed_df.isnull().sum()

Area        0
Bathroom    0
Parking     0
Per_Sqft    0
dtype: int64

In [86]:
object_cols.columns

Index(['Furnishing', 'Locality', 'Status', 'Transaction', 'Type'], dtype='object')

In [87]:
object_cols.isnull().sum()

Furnishing     5
Locality       0
Status         0
Transaction    0
Type           5
dtype: int64

In [88]:
object_cols.duplicated().sum()

np.int64(576)

In [89]:
object_cols.drop_duplicates(inplace=True)
object_cols.duplicated().sum()

np.int64(0)

In [91]:
object_cols.isnull().sum()

Furnishing     2
Locality       0
Status         0
Transaction    0
Type           2
dtype: int64

In [90]:
object_cols[["Furnishing"]].value_counts()

Furnishing    
Semi-Furnished    339
Unfurnished       220
Furnished         122
Name: count, dtype: int64

In [92]:
object_cols[["Status"]].value_counts()

Status       
Ready_to_move    641
Almost_ready      42
Name: count, dtype: int64

In [93]:
object_cols[["Type"]].value_counts()

Type         
Builder_Floor    342
Apartment        339
Name: count, dtype: int64

In [94]:
dummy= pd.get_dummies(object_cols["Type"],drop_first=True,dtype=int,dummy_na=True)
dummy

Builder_Floor  NaN
0                 1    0
1                 0    0
2                 0    0
3                 1    0
4                 1    0
...             ...  ...
1240              0    0
1241              1    0
1242              0    0
1244              1    0
1257              1    0

[683 rows x 2 columns]

In [95]:
import numpy as np
dummy = dummy.rename(columns={np.nan: 'nan_col'})
# Apply the condition
dummy.loc[dummy['nan_col'] == 1, 'Builder_Floor'] = np.nan
object_cols[["Type"]]=dummy[["Builder_Floor"]]

In [96]:
dummy= pd.get_dummies(object_cols["Transaction"],drop_first=True,dtype=int,dummy_na=True)
dummy

Resale  NaN
0          0    0
1          0    0
2          1    0
3          1    0
4          0    0
...      ...  ...
1240       1    0
1241       1    0
1242       1    0
1244       1    0
1257       1    0

[683 rows x 2 columns]

In [97]:
import numpy as np
dummy = dummy.rename(columns={np.nan: 'nan_col'})
# Apply the condition
dummy.loc[dummy['nan_col'] == 1, 'Resale'] = np.nan
object_cols[["Transaction"]]=dummy[["Resale"]]


In [98]:
dummy= pd.get_dummies(object_cols["Furnishing"],drop_first=True,dtype=int,dummy_na=True)
dummy

Semi-Furnished  Unfurnished  NaN
0                  1            0    0
1                  1            0    0
2                  0            0    0
3                  1            0    0
4                  1            0    0
...              ...          ...  ...
1240               1            0    0
1241               0            0    0
1242               0            1    0
1244               1            0    0
1257               0            1    0

[683 rows x 3 columns]

In [99]:
dummy = dummy.rename(columns={np.nan: 'nan_col'})
# Apply the condition
dummy.loc[dummy['nan_col'] == 1, ['Semi-Furnished','Unfurnished']] = np.nan
object_cols[['Semi-Furnished', 'Unfurnished']] = dummy[['Semi-Furnished', 'Unfurnished']]
object_cols = object_cols.drop('Furnishing', axis=1)

In [100]:
dummy= pd.get_dummies(object_cols["Status"],drop_first=True,dtype=int,dummy_na=True)
dummy

Ready_to_move  NaN
0                 1    0
1                 1    0
2                 1    0
3                 1    0
4                 1    0
...             ...  ...
1240              1    0
1241              1    0
1242              1    0
1244              1    0
1257              1    0

[683 rows x 2 columns]

In [101]:
dummy = dummy.rename(columns={np.nan: 'nan_col'})
# Apply the condition
dummy.loc[dummy['nan_col'] == 1, 'Ready_to_move'] = np.nan
object_cols[["Status"]]=dummy[["Ready_to_move"]]

In [102]:
object_cols

Locality  Status  Transaction  \
0                                      Rohini Sector 25     1.0          0.0   
1                J R Designers Floors, Rohini Sector 24     1.0          0.0   
2                   Citizen Apartment, Rohini Sector 13     1.0          1.0   
3                                      Rohini Sector 24     1.0          1.0   
4     Rohini Sector 24 carpet area 650 sqft status R...     1.0          0.0   
...                                                 ...     ...          ...   
1240                                  Chittaranjan Park     1.0          1.0   
1241  Chittaranjan Park carpet area 270 sqyrd status...     1.0          1.0   
1242                                  Chittaranjan Park     1.0          1.0   
1244                             Nehru Enclave, Kalkaji     1.0          1.0   
1257                          Chittaranjan Park Block A     1.0          1.0   

      Type  Semi-Furnished  Unfurnished  
0      1.0             1.0          0.0  
1      0.0             1.0          0.0  
2      0.0             0.0          0.0  
3      1.0             1.0          0.0  
4      1.0             1.0          0.0  
...    ...             ...          ...  
1240   0.0             1.0          0.0  
1241   1.0             0.0          0.0  
1242   0.0             0.0          1.0  
1244   1.0             1.0          0.0  
1257   1.0             0.0          1.0  

[683 rows x 6 columns]

In [103]:
object_cols

Locality  Status  Transaction  \
0                                      Rohini Sector 25     1.0          0.0   
1                J R Designers Floors, Rohini Sector 24     1.0          0.0   
2                   Citizen Apartment, Rohini Sector 13     1.0          1.0   
3                                      Rohini Sector 24     1.0          1.0   
4     Rohini Sector 24 carpet area 650 sqft status R...     1.0          0.0   
...                                                 ...     ...          ...   
1240                                  Chittaranjan Park     1.0          1.0   
1241  Chittaranjan Park carpet area 270 sqyrd status...     1.0          1.0   
1242                                  Chittaranjan Park     1.0          1.0   
1244                             Nehru Enclave, Kalkaji     1.0          1.0   
1257                          Chittaranjan Park Block A     1.0          1.0   

      Type  Semi-Furnished  Unfurnished  
0      1.0             1.0          0.0  
1      0.0             1.0          0.0  
2      0.0             0.0          0.0  
3      1.0             1.0          0.0  
4      1.0             1.0          0.0  
...    ...             ...          ...  
1240   0.0             1.0          0.0  
1241   1.0             0.0          0.0  
1242   0.0             0.0          1.0  
1244   1.0             1.0          0.0  
1257   1.0             0.0          1.0  

[683 rows x 6 columns]

In [105]:
object_cols.drop("Locality",axis=1,inplace=True)

In [106]:
object_cols = object_cols.astype("Int64")

In [107]:
object_cols

Status  Transaction  Type  Semi-Furnished  Unfurnished
0          1            0     1               1            0
1          1            0     0               1            0
2          1            1     0               0            0
3          1            1     1               1            0
4          1            0     1               1            0
...      ...          ...   ...             ...          ...
1240       1            1     0               1            0
1241       1            1     1               0            0
1242       1            1     0               0            1
1244       1            1     1               1            0
1257       1            1     1               0            1

[683 rows x 5 columns]

In [108]:
scaler = StandardScaler()
object_cols_sc=scaler.fit_transform(object_cols)
object_cols_sc

array([[ 0.25597387, -1.41266204,  0.99560437,  1.00441503, -0.6908136 ],
       [ 0.25597387, -1.41266204, -1.00441503,  1.00441503, -0.6908136 ],
       [ 0.25597387,  0.7078834 , -1.00441503, -0.99560437, -0.6908136 ],
       ...,
       [ 0.25597387,  0.7078834 , -1.00441503, -0.99560437,  1.44756849],
       [ 0.25597387,  0.7078834 ,  0.99560437,  1.00441503, -0.6908136 ],
       [ 0.25597387,  0.7078834 ,  0.99560437, -0.99560437,  1.44756849]])

In [109]:
imputer = KNNImputer(n_neighbors=5)
object_cols_imput=imputer.fit_transform(object_cols_sc)
object_cols_imput

array([[ 0.25597387, -1.41266204,  0.99560437,  1.00441503, -0.6908136 ],
       [ 0.25597387, -1.41266204, -1.00441503,  1.00441503, -0.6908136 ],
       [ 0.25597387,  0.7078834 , -1.00441503, -0.99560437, -0.6908136 ],
       ...,
       [ 0.25597387,  0.7078834 , -1.00441503, -0.99560437,  1.44756849],
       [ 0.25597387,  0.7078834 ,  0.99560437,  1.00441503, -0.6908136 ],
       [ 0.25597387,  0.7078834 ,  0.99560437, -0.99560437,  1.44756849]])

In [110]:
data_imputed = scaler.inverse_transform(object_cols_imput)
data_imputed

array([[1., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       ...,
       [1., 1., 0., 0., 1.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 0., 1.]])

In [111]:
imputed_df = pd.DataFrame(data_imputed,columns=object_cols.columns)
imputed_df

Status  Transaction  Type  Semi-Furnished  Unfurnished
0       1.0          0.0   1.0             1.0          0.0
1       1.0          0.0   0.0             1.0          0.0
2       1.0          1.0   0.0             0.0          0.0
3       1.0          1.0   1.0             1.0          0.0
4       1.0          0.0   1.0             1.0          0.0
..      ...          ...   ...             ...          ...
678     1.0          1.0   0.0             1.0          0.0
679     1.0          1.0   1.0             0.0          0.0
680     1.0          1.0   0.0             0.0          1.0
681     1.0          1.0   1.0             1.0          0.0
682     1.0          1.0   1.0             0.0          1.0

[683 rows x 5 columns]

In [131]:
object_cols = imputed_df.round().astype("Int64")
object_cols

Status  Transaction  Type  Semi-Furnished  Unfurnished
0         1            0     1               1            0
1         1            0     0               1            0
2         1            1     0               0            0
3         1            1     1               1            0
4         1            0     1               1            0
..      ...          ...   ...             ...          ...
678       1            1     0               1            0
679       1            1     1               0            0
680       1            1     0               0            1
681       1            1     1               1            0
682       1            1     1               0            1

[683 rows x 5 columns]

In [147]:
final_dataset=pd.concat([int_cols,float_cols,object_cols],axis=1)
# Impute missing values in the final dataset
imputer = KNNImputer(n_neighbors=5)
final_dataset = imputer.fit_transform(final_dataset)
final_dataset = pd.DataFrame(final_dataset, columns=pd.concat([int_cols,float_cols,object_cols],axis=1).columns)

In [149]:
independent=final_dataset.drop("Price",axis=1)
dependent=final_dataset["Price"]

In [150]:
from sklearn.model_selection import train_test_split
X_test,X_train,Y_test,Y_train=train_test_split(independent,dependent,test_size=0.30,random_state=42)

In [151]:
from sklearn.linear_model import LinearRegression

In [152]:
model=LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [153]:
y_pred=model.predict(X_test)

In [154]:
y_pred

array([ 25971186.20887985,  27052501.8506906 ,  20785400.20224548,
         8642024.92217053,   6241647.76871221,  -9125946.81720039,
        24676701.73730284,  12436604.55096963,  30737579.41354095,
        69316303.95430014,   7209932.45773823,   6823981.51909975,
         4551979.84719239,   7368325.59144756,  13495305.19491537,
         4403632.74110215,  17944523.75306507,  28302566.87399673,
         6027417.17327031,  24022141.10419946,  23776025.84329506,
        14817428.64935295,  10067103.00251576,  17798329.0334348 ,
         9191938.63202799,  49206288.36348548,  33288949.98820276,
        37983611.36734144,  39588354.36073631,  19171273.01092689,
        15833389.52706714,  21400923.08599157,  28580032.33320943,
         6698651.52782811,  36737632.64969636,  31676686.82751478,
        13375530.53680247,  23054364.0935569 ,  25326453.01230073,
        21125736.74429455,   7532496.76905058,  15713009.23212302,
        55338070.06765936,  37453807.82222062,   -413063.44246

In [141]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)
r_score

0.27955615612232254